[package]
name = "capture-agent-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.capture-agent]
path = ".."

[[bin]]
name = "parse_packet"
path = "fuzz_targets/parse_packet.rs"
test = false
doc = false
bench = false

[[bin]]
name = "http2_reassembly"
path = "fuzz_targets/http2_reassembly.rs"
test = false
doc = false
bench = false
