// JAM-185: the `osi-mon` terminal client that /api/install writes must show
// only values with a real producer. These tests run the generated program
// itself, extracted from the installer, against a fake /api/stream, and
// check what it prints.
import { describe, expect, it } from 'vitest';
import vm from 'node:vm';
import type { NextRequest } from 'next/server';
import { GET } from '@/app/api/install/route';

const ESC = '\u001b';

async function installerScript(host = 'localhost:3000'): Promise<string> {
  const req = { headers: new Headers({ host }) } as unknown as NextRequest;
  return (await GET(req)).text();
}

// The program between the installer's `cat << 'EOF' > "$CLI_FILE"` and the
// heredoc's closing `EOF` line, exactly as the installer writes it to disk.
async function osiMonSource(host?: string): Promise<string> {
  const script = await installerScript(host);
  const start = script.indexOf(`cat << 'EOF' > "$CLI_FILE"\n`);
  expect(start).toBeGreaterThan(-1);
  const body = script.slice(start).split('\n').slice(1);
  const end = body.indexOf('EOF');
  expect(end).toBeGreaterThan(-1);
  return body.slice(0, end).join('\n');
}

interface FakeResponse {
  emit(event: 'data' | 'end', chunk?: string): void;
}

// Runs osi-mon in a sandbox whose `http`/`https` modules hand back a
// response the test drives, and whose stdout is captured. Timers never fire
// on their own.
async function runOsiMon(opts: { statusCode?: number; connectError?: string; host?: string } = {}) {
  const source = (await osiMonSource(opts.host)).replace(/^#!.*\n/, '');
  const writes: string[] = [];
  const requested: string[] = [];
  const handlers: Record<string, ((chunk?: string) => void)[]> = {};
  const errorHandlers: ((err: Error) => void)[] = [];
  const response = {
    statusCode: opts.statusCode ?? 200,
    setEncoding() {},
    resume() {},
    on(event: string, fn: (chunk?: string) => void) {
      (handlers[event] ??= []).push(fn);
      return response;
    },
  };
  const fakeHttp = {
    get(url: URL, _options: unknown, onResponse: (res: typeof response) => void) {
      requested.push(String(url));
      const req = {
        on(event: string, fn: (err: Error) => void) {
          if (event === 'error') errorHandlers.push(fn);
          return req;
        },
      };
      if (opts.connectError) {
        queueMicrotask(() => errorHandlers.forEach((fn) => fn(new Error(opts.connectError))));
      } else {
        queueMicrotask(() => onResponse(response));
      }
      return req;
    },
  };
  const context = vm.createContext({
    require: (name: string) => {
      if (name === 'http' || name === 'https') return fakeHttp;
      throw new Error(`unexpected require(${name})`);
    },
    process: { stdout: { write: (s: string) => writes.push(s) }, on() {} },
    console: { log: (s: string) => writes.push(s + '\n') },
    setInterval: () => 0,
    setTimeout: () => 0,
    URL,
    Date,
  });
  vm.runInContext(source, context);
  await new Promise((resolve) => setTimeout(resolve, 0));
  const res: FakeResponse = {
    emit(event, chunk) {
      (handlers[event] ?? []).forEach((fn) => fn(chunk));
    },
  };
  return {
    res,
    requested,
    // The most recent full-screen frame.
    lastFrame: () => writes[writes.length - 1] ?? '',
    sse: (event: unknown) => res.emit('data', `data: ${JSON.stringify(event)}\n\n`),
  };
}

const systemStats = {
  type: 'system_stats',
  stats: {
    hostname: 'osi-gw-01',
    interfaceName: 'en0',
    ipAddress: '192.168.1.104',
    rxTotalMbps: 4.68,
    txTotalMbps: 3.7,
    rxPpsTotal: 480,
    txPpsTotal: 220,
    totalPacketsCaptured: 184200,
  },
};

const layerUpdate = {
  type: 'layer_update',
  layers: [
    { layer: 3, rxSpeed: 2_500_000, txSpeed: 900, rxPacketsPerSec: 0, txPacketsPerSec: 0, totalBytes: 1, errorRate: 0, activeSockets: 5, sparkline: [] },
    { layer: 4, rxSpeed: 2_500_000, txSpeed: 900, rxPacketsPerSec: 0, txPacketsPerSec: 0, totalBytes: 1, errorRate: 0, activeSockets: 5, sparkline: [] },
    { layer: 7, rxSpeed: 1536, txSpeed: 585, rxPacketsPerSec: 0, txPacketsPerSec: 0, totalBytes: 1, errorRate: 0, activeSockets: 5, sparkline: [] },
  ],
};

describe('osi-mon (generated by /api/install)', () => {
  it('contains no fabricated or hardcoded measurements', async () => {
    const source = await osiMonSource();
    expect(source).not.toMatch(/Math\.random/);
    expect(source).not.toMatch(/UPTIME/i);
    expect(source).not.toMatch(/\d+(\.\d+)?\s*Gbps/);
    expect(source).not.toMatch(/10GBase|Fiber PHY/);
  });

  it('reads the live stream from the server it was installed from', async () => {
    const { requested } = await runOsiMon();
    expect(requested).toEqual(['http://localhost:3000/api/stream']);
  });

  it('shows no figures at all until the agent has reported some', async () => {
    const { lastFrame } = await runOsiMon();
    expect(lastFrame()).toMatch(/waiting for the agent/i);
    expect(lastFrame()).not.toMatch(/\d\s*(B\/s|KB\/s|MB\/s|Mbps|pps)/);
  });

  it('prints exactly the values the agent reported', async () => {
    const run = await runOsiMon();
    run.sse({ type: 'connection_status', connected: true });
    run.sse(systemStats);
    run.sse(layerUpdate);
    const frame = run.lastFrame();
    expect(frame).toContain('osi-gw-01');
    expect(frame).toContain('en0');
    expect(frame).toContain('192.168.1.104');
    expect(frame).toContain('RX 4.68 Mbps');
    expect(frame).toContain('TX 3.70 Mbps');
    expect(frame).toContain('RX 480 pps');
    expect(frame).toContain('TX 220 pps');
    expect(frame).toContain('184200 packets captured');
    expect(frame).toMatch(/L7: APPLICATION[^\n]*RX 1\.5 KB\/s[^\n]*TX 585 B\/s/);
    expect(frame).toMatch(/L3: NETWORK[^\n]*RX 2\.38 MB\/s[^\n]*TX 900 B\/s/);
  });

  it('says which layers the agent cannot measure separately instead of inventing a number', async () => {
    const run = await runOsiMon();
    run.sse(systemStats);
    run.sse(layerUpdate);
    const frame = run.lastFrame();
    for (const name of ['L6: PRESENTATION', 'L5: SESSION', 'L2: DATA LINK', 'L1: PHYSICAL']) {
      expect(frame).toMatch(new RegExp(`${name}[^\\n]*not measured separately`));
    }
  });

  it('handles events split across chunks', async () => {
    const run = await runOsiMon();
    const text = `data: ${JSON.stringify(systemStats)}\n\n`;
    run.res.emit('data', text.slice(0, 20));
    run.res.emit('data', text.slice(20));
    expect(run.lastFrame()).toContain('RX 4.68 Mbps');
  });

  it('reports a disconnected agent rather than its last figures as current', async () => {
    const run = await runOsiMon();
    run.sse(systemStats);
    run.sse({ type: 'connection_status', connected: false });
    expect(run.lastFrame()).toMatch(/agent disconnected/i);
    expect(run.lastFrame()).not.toContain('RX 4.68 Mbps');
  });

  it('reports a server it cannot reach instead of showing figures', async () => {
    const run = await runOsiMon({ connectError: 'connect ECONNREFUSED 127.0.0.1:3000' });
    expect(run.lastFrame()).toContain('ECONNREFUSED');
    expect(run.lastFrame()).not.toMatch(/Mbps/);
  });

  it('reports a non-200 stream response', async () => {
    const run = await runOsiMon({ statusCode: 421 });
    expect(run.lastFrame()).toContain('HTTP 421');
  });

  it('escapes control characters in agent-reported text before writing them to the terminal', async () => {
    const run = await runOsiMon();
    run.sse({ ...systemStats, stats: { ...systemStats.stats, hostname: `evil${ESC}]0;pwned\u0007host` } });
    const frame = run.lastFrame();
    expect(frame).toContain('evil\\x1b]0;pwned\\x07host');
    expect(frame).not.toContain(`${ESC}]0;`);
  });

  it('never contains a bare EOF line that would end the installer heredoc early', async () => {
    const source = await osiMonSource();
    const script = await installerScript();
    expect(script).toContain(source);
    expect(source.split('\n')).not.toContain('EOF');
  });
});
